[package]
name = "ecs_game_in_rust"
version = "0.1.1"
edition = "2021"
description = "This is a Entity Compnent System map for games (a simple test for rust programming)"
license = "MIT"



[dependencies]
eyre = "0.6.8"
thiserror = "1.0.38"